### ISSUE TITLE
Project Links

### ISSUE THREAD

**Issue by Tamunokuro** [Bornittah/recipe-app#9]
- Team mates for this Project @Bornittah and @Tamunokuro  
- Project Link: [Recipe app](https://github.com/Bornittah/recipe-app/projects/1)

**Comment by danmainah** [comment]
Hi @Tamunokuro and @Bornittah , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good description and correct info.
✔️  Good design


# Required Changes ♻️

- [ ] @Tamunokuro and @Bornittah great work on your kanban board, however, you forgot to add a task for ensuring there are no N+1 problems, also kindly ensure your number of points allocated to the task is equal to the amount of time required to solve the problem.
![image](https://user-images.githubusercontent.com/61408860/227917689-e24a2866-8b1a-485a-ada4-34f5b73f34c7.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
